-- =============================================
-- CCFT Study App — Vocab Terms Table
-- Central "brain" for all extracted terms
-- Readable by all authenticated users
-- =============================================

create table public.vocab_terms (
  id         uuid primary key default gen_random_uuid(),
  term       text not null unique,
  definition text not null,
  source     text not null,
  domains    text[] not null,
  created_at timestamptz not null default now()
);

alter table public.vocab_terms enable row level security;

-- All authenticated users can read all terms
create policy "Authenticated users can read vocab terms"
  on public.vocab_terms
  for select
  using (auth.role() = 'authenticated');

create index idx_vocab_terms_term on public.vocab_terms(term);
create index idx_vocab_terms_domains on public.vocab_terms using gin(domains);

-- =============================================
-- SEED: 120 terms from top 10 priority docs
-- =============================================

insert into public.vocab_terms (term, definition, source, domains) values
  ('Abduction', 'Movement away from the body''s midline', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Accuracy', 'Controlling movement direction or intensity', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Actin', 'Thin contractile protein filament in muscle', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Active', 'Certification in good standing; may use CCFT designation', 'CCFT_CandidateHandbook', array['D7']),
  ('Active shoulders', 'Most stable shoulder position when working against a load', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Acute training load', 'Most recent weekly training load', 'ijspt-12-697', array['D2']),
  ('Acute:chronic training load ratio', 'Acute load divided by chronic load; flags injury risk', 'ijspt-12-697', array['D2']),
  ('Adduction', 'Movement toward the body''s midline', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Adenosine triphosphate (ATP)', 'Energy currency for metabolic and neuromuscular demands', 'ijspt-12-697', array['D1', 'D2']),
  ('Agility', 'Minimizing transition time between movement patterns', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Alveoli', 'Membranous air sacs in lungs where gas exchange occurs', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('AMRAP', 'As Many Rounds/Reps As Possible; time-priority format', 'CFJ_English_L2_TrainingGuide', array['D2']),
  ('Angiogenesis', 'Formation of new capillaries in response to tissue oxygen need', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Appeal', 'Formal request for special consideration of certification status', 'CCFT_CandidateHandbook', array['D7']),
  ('Appendicular skeleton', 'Bones of the arms, legs, hands, and feet', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Approved Providers', 'Entities offering CEUs meeting CrossFit certification standards', 'CCFT_CandidateHandbook', array['D7']),
  ('Arginine Vasopressin (AVP)', 'Anti-diuretic hormone; induces water reabsorption', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Arteries', 'Vessels carrying oxygenated blood away from heart', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Arterioles', 'Small-diameter arterial vessels', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Atria', 'Two small upper heart chambers receiving blood', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Atrioventricular node', 'Cardiac timer delaying impulse to ventricles', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Auditory learners', 'Process information through hearing and repeating', 'TG_Online_Kids', array['D3', 'D5']),
  ('Axial skeleton', 'Skull, vertebral column, ribs, collarbones, sternum', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Balance', 'Controlling body''s center of gravity over support base', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Balance about the frontal plane', 'Maintaining balance bisecting athlete at mid-foot', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Biasing', 'Programming skewed too heavily toward specific elements', 'CFJ_English_L2_TrainingGuide', array['D2']),
  ('Biomotor abilities', 'Physical capacities developed or lost during injury/rehab', 'ijspt-12-697', array['D1', 'D2']),
  ('Body awareness', 'Understanding where one''s body is in space', 'TG_Online_Kids', array['D1', 'D5']),
  ('Cancellous bone', 'Spongy bone near epiphysis; absorbs mechanical stress', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Capillaries', 'Micron-scale vessels allowing single blood cell passage', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Cardiovascular/Respiratory Endurance', 'Body''s ability to gather, process, and deliver oxygen', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Certified CrossFit Trainer (CCFT)', 'Advanced credential demonstrating coaching knowledge', 'CCFT_CandidateHandbook', array['D7']),
  ('Chipper', 'Longer workout with multiple movements done in sequence', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Chronic training load', 'Four-week average of training work performed', 'ijspt-12-697', array['D2']),
  ('Compact bone', 'Mineralized connective tissue in bone shaft', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Complaint', 'Communication expressing dissatisfaction about certification program', 'CCFT_CandidateHandbook', array['D7']),
  ('Completion window', 'Forecasted time or rep count for a scaled workout', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Complexity', 'Neurologic/organic elements combining general physical skills', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Consistency', 'Reliable repetition of sound mechanics across workouts', 'CFJ_English_Level1_TrainingGuide', array['D2', 'D3']),
  ('Constantly varied', 'Programming with broad variance in mode, exercise, pathway', 'CFJ_English_Level1_TrainingGuide', array['D2']),
  ('Contact hour', 'Clock hours of direct participation in professional development', 'CCFT_CandidateHandbook', array['D7']),
  ('Continuing Education Units (CEUs)', 'Credits based on contact hours; 1 CEU = 1 hour', 'CCFT_CandidateHandbook', array['D7']),
  ('Continuing Professional Development (CPD)', 'Ongoing learning to advance professional knowledge and skills', 'CCFT_CandidateHandbook', array['D7']),
  ('Coordination', 'Combining distinct movement patterns into one movement', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D5']),
  ('Core-to-extremity movement', 'Contraction sequence from large core muscles to extremities', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Correcting', 'Facilitating better mechanics via visual, verbal, tactile cues', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Couplet', 'Workout combining two movements', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Demonstration', 'Providing accurate visual example of a movement', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Dose-response relationship', 'Interaction between training input and athlete response', 'ijspt-12-697', array['D2']),
  ('Dynamic faults', 'Faults observed while athlete is moving between positions', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Early masters', 'Older adults with still-high physical capacity', 'sme_masters_trainingguide', array['D5']),
  ('Energy balance model', 'Calories in minus calories out determines weight change', 'TG_Online_Kids', array['D6']),
  ('Exercise-Associated Hyponatremia (EAH)', 'Dangerous dilution of serum sodium from fluid overconsumption', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D6']),
  ('Experience Level', 'Athlete classification guiding scaling: Beginner to Experienced', 'CFJ_2015_10_Scaling_Gordon_4', array['D2', 'D4']),
  ('Expired', 'Certification forfeited due to non-compliance with recertification', 'CCFT_CandidateHandbook', array['D7']),
  ('Extension', 'Opens the angle of a joint', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('External training load', 'Work performed by athlete (distance, weight, volume)', 'ijspt-12-697', array['D2']),
  ('False negative belief', 'Athlete believes worse than actual capacity; over-scales', 'sme_masters_trainingguide', array['D5']),
  ('False positive belief', 'Athlete believes better than actual capacity; reckless scaling', 'sme_masters_trainingguide', array['D5']),
  ('Flexibility', 'Maximizing range of motion at a given joint', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Flexion', 'Closes the angle of a joint', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Form', 'Normative value applied to mechanics and technique', 'CFJ_English_Level1_TrainingGuide', array['D3']),
  ('Functional movements', 'Natural compound movements producing high power output', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D3']),
  ('General movement patterns', 'Broad movement category a workout targets', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('General physical preparedness (GPP)', 'Broad fitness across all domains; not sport-specific', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Glycolytic system', 'Multistep ATP pathway using glucose without oxygen', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D2']),
  ('Group Management', 'Organizing class flow, space, equipment, and participants', 'CFJ_English_L2_TrainingGuide', array['D3', 'D5']),
  ('High Intensity', 'Defined as power (force x distance / time)', 'CFJ_English_Level1_TrainingGuide', array['D2']),
  ('Hyperinsulinemia', 'Response to chronically elevated blood sugar; triggers fat storage', 'TG_Online_Kids', array['D6']),
  ('Hypertonia', 'Overactive neuromuscular response; increased muscle tone', 'TG_Online_Kids', array['D1', 'D5']),
  ('Hyponatremia', 'Low blood sodium from excess fluid intake', 'CFJ_Anatomy_Physiology_Primer', array['D1', 'D6']),
  ('Hypotonia', 'Low muscle tone; poor neuromuscular communication', 'TG_Online_Kids', array['D1', 'D5']),
  ('Intended stimulus', 'Specific training effect a workout is designed to produce', 'CFJ_English_L2_TrainingGuide', array['D2']),
  ('Intensity', 'Foundational priority of CrossFit; power output', 'CFJ_English_Level1_TrainingGuide', array['D2']),
  ('Internal training load', 'Athlete''s physiological response to planned training', 'ijspt-12-697', array['D2']),
  ('Kids (age group)', 'Ages 5-12 in CrossFit Kids programming', 'TG_Online_Kids', array['D5']),
  ('Kinesthetic learners', 'Learn best through physical movement and exploration', 'TG_Online_Kids', array['D3', 'D5']),
  ('Late masters', 'Significantly deconditioned older adults, often 55+', 'sme_masters_trainingguide', array['D5']),
  ('Learning Needs Assessment (LNA)', 'Mandatory self-assessment survey for CPD planning', 'CCFT_CandidateHandbook', array['D7']),
  ('Leptin', 'Hormone signaling energy sufficiency; reduces food reward', 'TG_Online_Kids', array['D6']),
  ('Masters athlete', 'Older adult engaged in CrossFit training', 'sme_masters_trainingguide', array['D5']),
  ('Mechanics', 'Physics of movement: leverage, torque, force, power', 'CFJ_English_Level1_TrainingGuide', array['D3', 'D4']),
  ('Metabolic perturbation model', 'Refined carbs cause hyperinsulinemia and fat deposition', 'TG_Online_Kids', array['D6']),
  ('Midline stabilization', 'Maintaining spine''s natural curve under load or movement', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Movement substitution', 'Replacing a movement entirely when unsafe to perform', 'sme_masters_trainingguide', array['D5']),
  ('Muted hip', 'Hip that never flexes; driven by quads without posterior chain', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Myosin', 'Thick contractile protein filament in muscle', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Neuromotor control', 'Combined neurological and musculoskeletal action for movement', 'TG_Online_Kids', array['D1', 'D5']),
  ('Novice''s curse', 'Rushing past fundamentals toward complex movements', 'Virtuosity', array['D3']),
  ('Oxidative system', 'Aerobic pathway using Krebs cycle for sustained ATP', 'ijspt-12-697', array['D1', 'D2']),
  ('Phosphagen system', 'ATP-PCr energy pathway; high rate, very limited capacity', 'ijspt-12-697', array['D1', 'D2']),
  ('Points of Performance', 'Technical standards for correct movement execution', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Posterior chain', 'Hamstrings, glutes, and spinal erectors on back of body', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Power', 'Force x distance / time; muscular units applying max force quickly', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D2']),
  ('Pre-Scaled Workouts', 'Pre-designed scaled versions for Beginner/Intermediate levels', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Presence and Attitude', 'Creating positive, engaging learning environment with empathy', 'CFJ_English_L2_TrainingGuide', array['D3', 'D5']),
  ('Pretesting', 'Including 20 unscored exam questions for future evaluation', 'CCFT_CandidateHandbook', array['D7']),
  ('Proprioceptive system', 'Receptors providing joint position and pressure information', 'TG_Online_Kids', array['D1', 'D5']),
  ('Repeated sprint ability (RSA)', 'Ability to repeat near-maximal efforts with brief recovery', 'ijspt-12-697', array['D2']),
  ('Repetition budget', 'Weekly volume cap for high-risk movements in aging athletes', 'sme_masters_trainingguide', array['D5']),
  ('Return to Play (RTP)', 'Process transitioning from injury to full sport participation', 'ijspt-12-697', array['D2']),
  ('Revoked', 'Certification permanently removed after failed appeal', 'CCFT_CandidateHandbook', array['D7']),
  ('Rhabdomyolysis', 'Muscle breakdown releasing cell contents into bloodstream', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D6']),
  ('ROM (Range of Motion)', 'Distance component of movement; critical to power output', 'CFJ_2015_10_Scaling_Gordon_4', array['D2', 'D4']),
  ('Rx / As Prescribed', 'Workout as originally programmed; long-term goal', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Safe ROM', 'Range maintaining points of performance; varies day to day', 'CFJ_2015_10_Scaling_Gordon_4', array['D2', 'D4']),
  ('Sarcomere', 'Functional contractile unit of muscle; Z-line to Z-line', 'CFJ_Anatomy_Physiology_Primer', array['D1']),
  ('Scaling', 'Adjusting workouts to preserve intended stimulus', 'CFJ_2015_10_Scaling_Gordon_4', array['D2', 'D4']),
  ('Scope of Practice', 'Defined boundaries of what a CCFT may do professionally', 'CCFT_CandidateHandbook', array['D7']),
  ('Seeing', 'Distinguishing good from poor mechanics in static/dynamic positions', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Self-efficacy', 'Belief in one''s capability to make a specific change', 'CFJ_English_L2_TrainingGuide', array['D3']),
  ('Session Rating of Perceived Exertion (sRPE)', 'Internal load metric: RPE multiplied by session duration', 'ijspt-12-697', array['D2']),
  ('Singlet', 'Single-movement workout', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Speed', 'Minimizing the time cycle of a repeated movement', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('SpO2 (blood oxygen saturation)', 'Blood oxygen measurement; guideline not below 90', 'sme_masters_trainingguide', array['D5']),
  ('Stamina', 'Body''s ability to process, store, and utilize energy', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('StARRT framework', 'Risk assessment: health risk, activity risk, risk tolerance', 'ijspt-12-697', array['D2']),
  ('Static faults', 'Faults at positions where athlete pauses or is stationary', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Stimulus (stimuli)', 'Intended training effect of a programmed workout', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Strength', 'Ability to apply force; productive application of force', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Style', 'Individual movement signature; no bearing on form', 'CFJ_English_Level1_TrainingGuide', array['D3']),
  ('Suspended', 'Certification not in good standing due to disciplinary action', 'CCFT_CandidateHandbook', array['D7']),
  ('Tabata interval', '20 sec work / 10 sec rest repeated 8 times', 'CFJ_English_Level1_TrainingGuide', array['D2']),
  ('Task-Priority Workout', 'Workout measured by completion time', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Teaching', 'Effectively articulating and instructing movement mechanics', 'CFJ_English_L2_TrainingGuide', array['D3', 'D4']),
  ('Technique', 'Method to successfully complete a movement', 'CFJ_English_Level1_TrainingGuide', array['D3']),
  ('Teens (age group)', 'Ages 12-18 in CrossFit Kids programming', 'TG_Online_Kids', array['D5']),
  ('10 General Physical Skills', 'Ten capacities defining comprehensive fitness', 'CFJ_English_Level1_TrainingGuide', array['D1']),
  ('Three metabolic pathways', 'Phosphagen, glycolytic, and oxidative energy systems', 'CFJ_English_Level1_TrainingGuide', array['D1', 'D2']),
  ('Three modalities', 'Monostructural, gymnastics, weightlifting', 'CFJ_English_Level1_TrainingGuide', array['D2']),
  ('Threshold training', 'Pushing intensity while maintaining sound mechanics', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Time Domain', 'Workout duration determining primary metabolic pathway', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Time-Priority Workout', 'Workout measured by rounds/reps in fixed time', 'CFJ_2015_10_Scaling_Gordon_4', array['D2']),
  ('Training Impulse (TRIMP)', 'Load score from HR zone weighting across a session', 'ijspt-12-697', array['D2']),
  ('Triple extension', 'Extension of hip, knee, and ankle from violent hip drive', 'CFJ_English_L2_TrainingGuide', array['D4']),
  ('Triplet', 'Workout combining three movements', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('True negative belief', 'Athlete has limitations, knows it, scales well', 'sme_masters_trainingguide', array['D5']),
  ('True positive belief', 'Athlete has good capacity and accurate self-assessment', 'sme_masters_trainingguide', array['D5']),
  ('Variance', 'Programming variety across movements, loads, time domains', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Virtuosity', 'Performing the common uncommonly well', 'Virtuosity', array['D3', 'D4']),
  ('Volume', 'Additional training beyond one CrossFit workout per day', 'CFJ_2016_02_Volume_Hobart', array['D2']),
  ('Wellness athlete', 'Masters athlete training for health, not competition', 'sme_masters_trainingguide', array['D5']),
  ('Zone Diet', '40% carb, 30% protein, 30% fat macronutrient prescription', 'CFJ_English_Level1_TrainingGuide', array['D6'])
on conflict (term) do nothing;
